[project]
name = "functions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "firebase-admin>=6.7.0",
    "firebase-functions>=0.4.2",
    "jinja2>=3.1.6",
    "specklepy>=2.21.3",
]
