name: Detect Changes

on:
  workflow_call:
    outputs:
      deploy_functions:
        description: "Should deploy functions?"
        value: ${{ jobs.detect.outputs.deploy_functions }}
      deploy_hosting:
        description: "Should deploy hosting?"
        value: ${{ jobs.detect.outputs.deploy_hosting }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      deploy_functions: ${{ steps.check_changes.outputs.deploy_functions }}
      deploy_hosting: ${{ steps.check_changes.outputs.deploy_hosting }}
    steps:
      - name: Checkout Repository (Ensure Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get full commit history

      - name: Fetch and Compare Changes
        run: |
          # Fetch the latest main branch and ensure it's up to date
          git fetch origin main --depth=1
          git checkout -B main origin/main
          git reset --soft origin/main
      
          # Ensure we get the actual SHA instead of a branch reference
          BASE_SHA=$(git rev-parse origin/main)
          echo "BASE_SHA=$BASE_SHA" >> "$GITHUB_ENV"
          echo "Comparing against: $BASE_SHA"
      
          # Debugging - See if changes exist
          echo "===== DEBUG: GIT STATUS ====="
          git status
          echo "===== DEBUG: GIT LOG ====="
          git log --oneline -5
          echo "===== DEBUG: GIT DIFF ====="
          git diff --name-status $BASE_SHA..HEAD
      
          # Detect Changes
          CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD)
          echo "Changed files: $CHANGED_FILES"
      
          # Detect Functions changes
          if echo "$CHANGED_FILES" | grep -E '^functions/' > /dev/null; then
            echo "Deploying Functions!"
            echo "deploy_functions=true" >> "$GITHUB_ENV"
            echo "deploy_functions=true" >> "$GITHUB_OUTPUT"
          else
            echo "No function changes detected."
            echo "deploy_functions=false" >> "$GITHUB_ENV"
            echo "deploy_functions=false" >> "$GITHUB_OUTPUT"
          fi
      
          # Detect Hosting (public/) changes
          if echo "$CHANGED_FILES" | grep -E '^public/|^firebase.json' > /dev/null; then
            echo "Deploying Hosting!"
            echo "deploy_hosting=true" >> "$GITHUB_ENV"
            echo "deploy_hosting=true" >> "$GITHUB_OUTPUT"
          else
            echo "No hosting changes detected."
            echo "deploy_hosting=false" >> "$GITHUB_ENV"
            echo "deploy_hosting=false" >> "$GITHUB_OUTPUT"
          fi

