name: Detect Changes

on:
  workflow_call:
    outputs:
      deploy_functions:
        description: "Detects if Firebase Functions should be deployed"
        value: ${{ jobs.detect_changes.outputs.deploy_functions }}
      deploy_hosting:
        description: "Detects if Firebase Hosting should be deployed"
        value: ${{ jobs.detect_changes.outputs.deploy_hosting }}

permissions:
  contents: read
  pull-requests: read  # ✅ Allow PRs to access changed files

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      deploy_functions: ${{ steps.filter.outputs.functions }}
      deploy_hosting: ${{ steps.filter.outputs.hosting }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for proper diff detection

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Required for forked PRs
          filters: |
            functions:
              - 'functions/**'
            hosting:
              - 'public/**'
              - 'firebase.json'
