name: CI Tests for Dependency Updates (No Deploy)

on:
  pull_request:
    branches:
      - main

jobs:
  test_firebase_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 🔹 Setup Firebase Authentication (Required for Emulators)
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      # 🔹 Setup Python Virtual Environment
      - name: Setup Python Virtual Environment
        run: |
          cd functions
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 🔹 Run Firebase Emulator Tests
      - name: Test Firebase Functions (No Deploy)
        run: firebase emulators:exec --only functions 'python -m unittest discover -s tests'

      # 🔹 If Tests Fail, Add PR Comment + Label (For Renovate/Dependabot)
      - name: Flag PR as Invalid if Tests Fail
        if: failure() && (github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]')
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ This dependency update **breaks Firebase functions**. Firebase requires a specific version of \`cloudevents\`. Please update Renovate/Dependabot configuration to prevent this."
          gh pr edit ${{ github.event.pull_request.number }} --add-label "invalid update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
