name: Deploy to Firebase on Merge

on:
  push:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      deploy_functions: ${{ steps.check.outputs.functions }}
      deploy_hosting: ${{ steps.check.outputs.hosting }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Relevant Changes
        id: check
        run: |
          echo "Checking for changes in functions/ and public/"
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed Files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -qE '^functions/'; then
            echo "✅ Functions changed!"
            echo "functions=true" >> $GITHUB_ENV
            echo "functions=true" >> $GITHUB_OUTPUT
          else
            echo "❌ No function changes detected."
            echo "functions=false" >> $GITHUB_ENV
            echo "functions=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -qE '^public/|firebase.json'; then
            echo "✅ Hosting changes detected!"
            echo "hosting=true" >> $GITHUB_ENV
            echo "hosting=true" >> $GITHUB_OUTPUT
          else
            echo "❌ No hosting changes detected."
            echo "hosting=false" >> $GITHUB_ENV
            echo "hosting=false" >> $GITHUB_OUTPUT
          fi



  # 🔹 Deploy Firebase Functions (Only if Backend Changes)
  deploy_functions:
    needs: detect_changes
    if: needs.detect_changes.outputs.deploy_functions == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 🔹 Setup Firebase Authentication (Because Firebase won't authenticate itself)
      # This sets up GOOGLE_APPLICATION_CREDENTIALS using a JSON file from GitHub Secrets.
      #
      #    WTF Google? Why is this not in the docs?
      #    If you don’t have the right service account:
      #    gcloud iam service-accounts list --project speckle-model-checker
      #
      #    If it still fails, you'll have to manually assign the "Service Account User" role:
      #    gcloud projects add-iam-policy-binding speckle-model-checker \
      #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
      #      --role="roles/iam.serviceAccountUser"
      #
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      # 🔹 Setup Python Virtual Environment (Because Firebase Functions would rather die than work without it)
      # 
      #    If it fails with "Missing virtual environment," do this manually:
      #    cd functions && python3 -m venv venv
      #    source venv/bin/activate && pip install -r requirements.txt
      #
      - name: Setup Python Virtual Environment
        run: |
          cd functions
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 🔹 Deploy Firebase Functions (Because why would this be easy?)
      #
      #    If you see permission errors, it’s because Google wants you to manually assign roles:
      #    gcloud projects add-iam-policy-binding speckle-model-checker \
      #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
      #      --role="roles/cloudfunctions.admin"
      #
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project speckle-model-checker

  # 🔹 Deploy Firebase Hosting (HTMX Static Files Only)
  #
  # Since this is an HTMX project, **no build step needed**.
  # We assume that your `public/` directory already contains everything needed.
  #
  #    If Hosting deploy fails, check IAM permissions:
  #    gcloud projects add-iam-policy-binding speckle-model-checker \
  #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
  #      --role="roles/firebasehosting.admin"
  #
  # 🚨 HTMX is here **purely to trigger the CEO**. No frameworks, no bloat, just vibes. 🚨
  #
  deploy_hosting:
    needs: detect_changes
    if: needs.detect_changes.outputs.deploy_hosting == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 🔹 Setup Firebase Authentication
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      # 🔹 Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          channelId: live
          projectId: speckle-model-checker
