name: Jon defensively tests for dependencies that dont work

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  test_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🐍 Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 🔹 Setup Virtual Environment
      - name: Setup Virtual Environment
        run: |
          cd functions
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      # 🔥 Test Dependency Installation
      - name: Install Dependencies (Fail If Conflicts)
        run: |
          cd functions
          source venv/bin/activate
          pip install -r requirements.txt

      # 🚨 Auto-Close PR If Failure (Only for Renovate)
      - name: Close Renovate PR if Dependencies Fail
        if: failure() && contains(github.actor, 'renovate')
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr comment $PR_NUMBER --body "⚠️ **Dependency Conflict!** This PR updates dependencies in a way that **breaks Firebase Functions**. Firebase requires specific package versions. Please adjust the Renovate config to avoid conflicts."
          gh pr close $PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

