name: Deploy Firebase Functions (Python)

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Authenticate Firebase and Fix GOOGLE_APPLICATION_CREDENTIALS Scope
      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "Setting GOOGLE_APPLICATION_CREDENTIALS..."
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json  # Use absolute path

      # Debugging Step: Check if JSON and ADC Work
      - name: Debug JSON and Check ADC
        run: |
          echo "Checking if JSON exists..."
          ls -lah $HOME/firebase-key.json
          echo "Checking JSON content (sanitized)..."
          head -n 5 $HOME/firebase-key.json  # Show first few lines for debugging
          echo "Checking GOOGLE_APPLICATION_CREDENTIALS..."
          echo $GOOGLE_APPLICATION_CREDENTIALS

      # Verify Firebase Authentication
      - name: Verify Firebase Authentication
        run: firebase projects:list --project speckle-model-checker

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Setup Python for Firebase Functions
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match your Firebase Functions Python version

      # Install Dependencies for Firebase Functions
      - name: Install Python Dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      # Deploy Firebase Cloud Functions (Python)
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project speckle-model-checker --debug
