name: Preview Firebase Hosting OR Test Firebase Functions on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  # 🔹 Deploy Firebase Hosting Preview (Only If Public/Frontend Changes)
  deploy_hosting:
    if: "contains(github.event.pull_request.changed_files, 'public/') || contains(github.event.pull_request.changed_files, 'firebase.json')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 🔹 Setup Firebase Authentication
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      # 🔹 Deploy to Firebase Hosting (Preview Only)
      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          projectId: speckle-model-checker
