name: Deploy to Firebase Hosting and Functions on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Deploy Firebase Cloud Functions (Python)
      - name: Deploy Firebase Functions
        uses: gannonk08/firebase-action-python@v0.0.1
        with:
          args: deploy --only functions --debug
        env:
          CREATE_VENV: true
          PROJECT_PATH: functions  # Ensure this is the correct directory for your Python functions
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          channelId: live
          projectId: speckle-model-checker
