name: Deploy Firebase Functions (Python)

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Set up Firebase Authentication (Application Default Credentials)
      - name: Authenticate Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' > $HOME/firebase-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Setup Python for Firebase Functions
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match the Python version in Firebase Functions

      # Install Dependencies for Firebase Functions
      - name: Install Python Dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      # Deploy Firebase Cloud Functions (Python)
      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only functions --project speckle-model-checker
