# Deploy to Firebase Hosting and Functions on merge to main

name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Python for Firebase Functions
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python Dependencies for Firebase Functions
      - name: Install Python Dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      # Deploy both Hosting and Functions
      - run: firebase deploy --only functions,hosting --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
