name: Deploy to Firebase Hosting and Functions on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Setup Python for Firebase Functions
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Match the Python version in Firebase Functions

      # Install Dependencies for Firebase Functions
      - name: Install Python Dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      # Authenticate Firebase using Service Account
      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"

      # Deploy Firebase Cloud Functions (Python)
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project speckle-model-checker

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          channelId: live
          projectId: speckle-model-checker

