name: Deploy to Firebase on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 🔹 Setup Firebase Authentication (Because Firebase won't authenticate itself)
      # This sets up GOOGLE_APPLICATION_CREDENTIALS using a JSON file from GitHub Secrets.
      #
      # WTF Google? Why is this not in the docs?
      #    If you don’t have the right service account:
      #    gcloud iam service-accounts list --project speckle-model-checker
      #
      #    If it still fails, you'll have to manually assign the "Service Account User" role:
      #    gcloud projects add-iam-policy-binding speckle-model-checker \
      #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
      #      --role="roles/iam.serviceAccountUser"
      #
      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      # 🔹 Setup Python Virtual Environment (Because Firebase Functions would rather die than work without it)
      # 
      #    If it fails with "Missing virtual environment," do this manually:
      #    cd functions && python3 -m venv venv
      #    source venv/bin/activate && pip install -r requirements.txt
      #
      - name: Setup Python Virtual Environment
        run: |
          cd functions
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 🔹 Deploy Firebase Functions (Because why would this be easy?)
      #
      #    If you see permission errors, it’s because Google wants you to manually assign roles:
      #    gcloud projects add-iam-policy-binding speckle-model-checker \
      #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
      #      --role="roles/cloudfunctions.admin"
      #
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project speckle-model-checker

      # 🔹 Install Dependencies & Build for Firebase Hosting (Because static sites are apparently rocket science)
      #
      - name: Install Frontend Dependencies & Build
        run: npm ci && npm run build

      # 🔹 Deploy to Firebase Hosting (Because this should have just been a single damn button)
      #
      #    If it fails, guess what? More manual permission fixes:
      #    gcloud projects add-iam-policy-binding speckle-model-checker \
      #      --member="serviceAccount:GITHUB_SERVICE_ACCOUNT_EMAIL" \
      #      --role="roles/firebasehosting.admin"
      #
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          channelId: live
          projectId: speckle-model-checker
