name: Preview Firebase Hosting OR Test Firebase Functions on PR

on:
  pull_request:
    branches:
      - main



jobs:
  
  detect_changes:
    uses: ./.github/workflows/detect_changes.yml  # Reuse detect_changes workflow
  
  # 🔹 Deploy Firebase Hosting Preview (Only If Public/Frontend Changes)
  deploy_hosting:
    needs: detect_changes
    if: needs.detect_changes.outputs.deploy_hosting == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}' | jq '.' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/firebase-key.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECKLE_MODEL_CHECKER }}
          channelId: live
          projectId: speckle-model-checker
